NAPT_ZIP_LINK : "http://naptan.app.dft.gov.uk/DataRequest/Naptan.ashx?format=csv"
DEFAULT_CRS : 'EPSG:27700'
DATA_DIR :  "./data"
EXT_ORDER :
  - feather
  - csv
  - zip
Urb_Rur_ZIP_LINK : https://www.arcgis.com/sharing/rest/content/items/3ce248e9651f4dc094f84a4c5de18655/data
NAPTAN_TYPES :
  NaptanCode: str
  CommonName: str
  Easting: int32
  Northing: int32
URB_RUR_TYPES:
  OA11CD: str
  RUC11CD: category
uk_LSOA_shp_file: "Lower_Layer_Super_Output_Areas__December_2011__Boundaries_EW_BGC.shp"
OA_boundaries_csv: 'https://opendata.arcgis.com/datasets/7763a773b61445128ed3251e27be5139_0.csv?outSR=%7B%22latestWkid%22%3A27700%2C%22wkid%22%3A27700%7D'
